sudo: required
services:
  - docker

before_install:
 - docker build -t meryemwehbe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true meryemwehbe/react-test npm test -- --coverage

after_success:
  - docker build -t meryemwehbe/multi-client ./client
  - docker build -t meryemwehbe/multi-nginx ./nginx
  - docker build -t meryemwehbe/multi-server ./server
  - docker build -t meryemwehbe/multi-worker ./worker
  #  Login in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push meryemwehbe/multi-client
  - docker push  meryemwehbe/multi-nginx
  - docker push  meryemwehbe/multi-server
  - docker push  meryemwehbe/multi-worker

